version: '3.8'

services:
  mpi_engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    container_name: mpi_engine
    ports:
      - "7072:8080"

  # c_engine:
  #   build:
  #     context: ./engineC
  #     dockerfile: Dockerfile
  #   container_name: c_engine
  #   ports:
  #     - "7073:8080"

  spark_engine:
    build:
      context: ./engineSpark
      dockerfile: Dockerfile
    container_name: spark_engine
    ports:
      - "7071:7071"
